### PR TITLE
Build a blog with Scully the Angular Static Site Generator and Webiny

### PR DESCRIPTION
**Pull request by gracegitt**

### CODE REVIEW

**Review by endymion1818 — CHANGES_REQUESTED** [review]
Please delete the `.git` folder and push again

**Review by gracegitt — COMMENTED** [review]
I have deleted the .git folder

**Comment by gracegitt** [comment]
> Please delete the `.git` folder and push again

I have deleted the .git folder

**Comment by endymion1818** [comment]
Sorry @gracegitt I see the only file has been changed is that the submodule was added. Please could you take another look. Please ping me on Slack if you need help.

**Comment by gracegitt** [comment]
> Sorry @gracegitt I see the only file has been changed is that the submodule was added. Please could you take another look. Please ping me on Slack if you need help.

Okay, let me have a look, I have pinged you.

**Pull request closed without merging**
